# Generated by Django 4.1.1 on 2022-12-19 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayForEvaluate",
            fields=[
                (
                    "EDP_BILL_NO",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ՎՃարման ID",
                    ),
                ),
                (
                    "EDP_AMOUNT",
                    models.IntegerField(default=1000, verbose_name="Գումար"),
                ),
                (
                    "EDP_REC_ACCOUNT",
                    models.IntegerField(default=110001952, verbose_name="Ստացողի ID"),
                ),
                (
                    "for_what",
                    models.CharField(
                        choices=[
                            ("Evaluate", "Գնահատման համար"),
                            ("Vote1", "Քվեարկել առաջին անգամ"),
                            ("Vote2", "Քվեարկել երկրորդ անգամ"),
                            ("Vote3", "Քվեարկել երորդ անգամ"),
                            ("Vote4", "Քվեարկել չորորդ անգամ"),
                            ("Vote4", "Քվեարկել հինգերորդ անգամ"),
                        ],
                        default="Evaluate",
                        max_length=100,
                        verbose_name="Ինչի համար՞",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Հաստատված է"),
                ),
            ],
            options={
                "verbose_name": "ՎՃարումներ",
                "verbose_name_plural": "ՎՃարումներ",
            },
        ),
    ]
