# Generated by Django 4.1.1 on 2022-12-17 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayForEvaluate",
            fields=[
                (
                    "EDP_BILL_NO",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "EDP_AMOUNT",
                    models.CharField(default=1000, editable=False, max_length=100),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.voterprofile",
                    ),
                ),
            ],
        ),
    ]
