# Generated by Django 4.1.1 on 2022-12-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("Idram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payforevaluate",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.voterprofile",
                verbose_name="Ընտրողի Էջ",
            ),
        ),
    ]
