# Generated by Django 4.1.1 on 2022-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payforevaluate",
            name="EDP_REC_ACCOUNT",
            field=models.IntegerField(default=110001952, editable=False),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="EDP_AMOUNT",
            field=models.IntegerField(default=1000, editable=False),
        ),
    ]
