# Generated by Django 4.1.1 on 2022-12-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Idram", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payforevaluate",
            name="for_what",
        ),
    ]
