# Generated by Django 4.1.1 on 2022-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_voterprofile_is_paid"),
        ("Idram", "0002_payforevaluate_edp_rec_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payforevaluate",
            name="for_what",
            field=models.CharField(
                choices=[("Գնահատում", "Գնահատման համար")],
                default=("Գնահատում", "Գնահատման համար"),
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="payforevaluate",
            name="profile",
        ),
        migrations.AddField(
            model_name="payforevaluate",
            name="profile",
            field=models.ManyToManyField(editable=False, to="accounts.voterprofile"),
        ),
    ]
