# Generated by Django 4.1.1 on 2022-12-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_voterprofile_is_paid"),
        ("Idram", "0003_payforevaluate_for_what_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payforevaluate",
            name="profile",
        ),
        migrations.AddField(
            model_name="payforevaluate",
            name="profile",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.voterprofile",
            ),
            preserve_default=False,
        ),
    ]
