# Generated by Django 4.1.1 on 2022-12-19 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_voterprofile_votes_count_alter_voterprofile_is_paid"),
        ("Idram", "0003_remove_payforevaluate_for_what"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "EDP_BILL_NO",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ՎՃարման ID",
                    ),
                ),
                ("EDP_AMOUNT", models.IntegerField(default=1, verbose_name="Գումար")),
                (
                    "EDP_REC_ACCOUNT",
                    models.IntegerField(default=110001952, verbose_name="Ստացողի ID"),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Հաստատված է"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.voterprofile",
                        verbose_name="Ընտրողի Էջ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ՎՃարումներ",
                "verbose_name_plural": "ՎՃարումներ",
            },
        ),
        migrations.DeleteModel(
            name="PayForEvaluate",
        ),
    ]
