# Generated by Django 4.1.1 on 2022-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idram", "0005_payforevaluate_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payforevaluate",
            name="for_what",
            field=models.CharField(
                choices=[("Գնահատում", "Գնահատման համար")],
                default=("Գնահատում", "Գնահատման համար"),
                max_length=100,
            ),
        ),
    ]
