# Generated by Django 4.1.1 on 2022-12-18 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_voterprofile_is_paid"),
        ("Idram", "0006_alter_payforevaluate_for_what"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payforevaluate",
            options={"verbose_name": "ՎՃարումներ", "verbose_name_plural": "ՎՃարումներ"},
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="EDP_AMOUNT",
            field=models.IntegerField(default=1000, verbose_name="Գումար"),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="EDP_BILL_NO",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="ՎՃարման ID",
            ),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="EDP_REC_ACCOUNT",
            field=models.IntegerField(default=110001952, verbose_name="Ստացողի ID"),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Հաստատված է"),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="for_what",
            field=models.CharField(
                choices=[
                    ("Evaluate", "Գնահատման համար"),
                    ("Vote1", "Քվեարկել առաջին անգամ"),
                    ("Vote2", "Քվեարկել երկրորդ անգամ"),
                    ("Vote3", "Քվեարկել երորդ անգամ"),
                    ("Vote4", "Քվեարկել չորորդ անգամ"),
                    ("Vote4", "Քվեարկել հինգերորդ անգամ"),
                ],
                default="Evaluate",
                max_length=100,
                verbose_name="Ինչի համար՞",
            ),
        ),
        migrations.AlterField(
            model_name="payforevaluate",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.voterprofile",
                verbose_name="Ընտրողի Էջ",
            ),
        ),
    ]
