# Generated by Django 4.1.1 on 2022-12-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_voterprofile_votes_count_alter_voterprofile_is_paid"),
        ("primaries_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("stage", models.IntegerField(default="1")),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.candidateprofile",
                    ),
                ),
                (
                    "voter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.voterprofile",
                    ),
                ),
            ],
        ),
    ]
