# Generated by Django 4.1.1 on 2022-12-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primaries_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfigs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3)],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
