# Generated by Django 4.1.1 on 2022-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primaries_app", "0002_globalconfigs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalconfigs",
            options={
                "verbose_name": "Կարգավորումներ",
                "verbose_name_plural": "Կարգավորումներ",
            },
        ),
        migrations.AlterField(
            model_name="globalconfigs",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Գնահատման Փուլ"),
                    ("2", "Առայիջին Քարոզարշավի Փուլ"),
                    ("3", "Առաջին Ընտրության Փուլ"),
                    ("4", "Երկրորդ Քարոզարշավի Փուլ"),
                    ("5", "Երկրորդ Ընտրության Փուլ"),
                    (None, "Ոչ ակտիվ փուլ"),
                ],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
