# Generated by Django 4.1.1 on 2022-12-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_voterprofile_votes_count_alter_voterprofile_is_paid"),
        ("primaries_app", "0003_alter_votingmodel_candidate_alter_votingmodel_voter"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votingmodel",
            unique_together={("voter", "candidate", "position", "stage")},
        ),
    ]
