# Generated by Django 4.1.1 on 2022-11-14 19:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="education",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="mig", verbose_name="Կրթություն"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="marital_status",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Ընտանեկան կարգավիճակ"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="political_experience",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Քաղաքական գործունեություն"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="work_experience",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Աշխատանքային գործունեություն"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="yerevan_rebuild",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Բարեփոխումներ մայրաքաղաքում"
            ),
        ),
    ]
