# Generated by Django 4.1.1 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_candidateprofile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Հաստատվել է Ադմինի կողմից։"
            ),
        ),
    ]
